Repository atomist-skills/skill, pull requests merged in 2020-10, with the labels that each got.

#82 Remove single dispatch and add support for webhooks
  index.ts
  lib/bundle.ts
  lib/context.ts
  lib/definition/skill.ts
  lib/function.ts
  lib/handler.ts
  lib/message.ts
  lib/payload.ts
  lib/prompt/util.ts
  lib/repository/filter.ts
  lib/script/skill_bundle.ts
  lib/script/skill_input.ts
  lib/secret/generic_resolver.ts
  lib/secret/provider.ts
  package.json
  test/function.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, changelog:added

#88 Remove DevEx skill category
  lib/script/skill_input.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve

#90 Consolidate skill categories
  graphql/schema.json
  lib/script/skill_input.ts
  lib/util.ts
  test/function.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#94 Add support for datalog subscriptions
  lib/bundle.ts
  lib/context.ts
  lib/function.ts
  lib/handler.ts
  lib/message.ts
  lib/payload.ts
  lib/script/skill_run.ts
  lib/secret/provider.ts
  test/function.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, changelog:added

#104 fix register script
  lib/script/skill_register.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve
